FROM hub.hmf.xyz/base/hmf-centos:8 AS base

RUN yum makecache && \
    yum install -y \
        krb5-workstation \
        krb5-libs \
        krb5-server && \
    yum clean all

COPY conf/krb5.conf /etc/krb5.conf
COPY conf/kdc.conf /var/kerberos/krb5kdc/kdc.conf
COPY conf/kadm5.acl /var/kerberos/krb5kdc/kadm5.acl

CMD ["/bin/bash"]