FROM hub.hmf.xyz/base/hmf-centos:8 AS base

RUN yum makecache && \
    yum install -y \
        krb5-workstation \
        krb5-libs \
        krb5-server && \
    yum clean all

ENV JAVA_HOME=/usr/lib/jvm/java
ENV PATH="$JAVA_HOME/bin:$PATH"

CMD ["/bin/bash"]