[supervisord]
nodaemon=true

[program:krb5kdc]
command=/usr/sbin/krb5kdc
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true

[program:kadmind]
command=/usr/sbin/kadmind
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
